### ISSUE TITLE
[Calendar] Equals

### ISSUE THREAD

**Issue by pavel-b-novikov** [Aloomenon/nsudotnet#1]
```date.Equals(DateTime.Now.Date)```

Объясните почему вы используете .Equals для сравнения дат. Не исправьте, а объясните. 

(ну, потом, конечно же, объясните)

**Comment by Aloomenon** [comment]
Использовал .Equals т.к. в какой-то момент в голову стукнуло, что это value-тип, а не простой, коим он и является. В принципе, никто не запрещает его использовать, что подтверждают примеры и описание метода на msdn. Поправил на оператор сравнения.

**Comment by pavel-b-novikov** [comment]
Value-тип и "простой"? Простите, а что тогда "простой"?

**Comment by Aloomenon** [comment]
В общем, чушь несу периодически. Я думал, что DateTime ссылочный, и именно по этому пользовался Equals, а т.к. он value-type то его можно сравнивать через "=="

**Comment by pavel-b-novikov** [comment]
А вот строки тоже можно сравнивать через двойное равно. Что - строка это value-type?

**Comment by Aloomenon** [comment]
Нет, для строк  == перегружен, и сравнивает их по значению, а не по ссылке

**Comment by pavel-b-novikov** [comment]
Ну вот это ближе к теме
