### ISSUE TITLE
[NumberGuesser] Парсеринг int-а

### ISSUE THREAD

**Issue by pavel-b-novikov** [Aloomenon/nsudotnet#2]
```Convert.ToInt32(str);```

Опять же - объясните что делает Convert, откуда он, как работает и почему выбор пал именно на него?

**Comment by Aloomenon** [comment]
Convert - класс с статическими методами конвертации, находящийся в пр-ве имен System. Открыв его исходник, я обнаружил (внезапно), что он использует Int32.Parse(). т.е. более оптимально будет использование именно Parse(). Выбор пал на конверт из-за того, что гугл при запросе аля: How to: Convert a String to a Number C# дал мне ссылку на гайд от мелкомягких, в котором был и Convert и Parse. Так как мне очень было лень читать, я запилил сразу с Convert.
