### ISSUE TITLE
[NumberGuesser] История

### ISSUE THREAD

**Issue by pavel-b-novikov** [Aloomenon/nsudotnet#3]
Я сначала подумал что до ФИТа вы занимались демокодингом, но видимо нет. Демокодер не пропустил бы такую ошибку.

На кой вам сохранять было ли введенное число в истории меньше или больше изначально загаданного. Сравнить по пути - не судьба?

**Comment by Aloomenon** [comment]
"Всю историю угадываний с пометкой больше/меньше рядом (для их сохранения используйте массив на 1000 элементов)" Была не правильна понята данная формулировка в тз, поэтому и сохранял. Поправил, закоммитил.
