### ISSUE TITLE
[LinesCounter] .GetFiles

### ISSUE THREAD

**Issue by pavel-b-novikov** [Aloomenon/nsudotnet#6]
Вы используете метод GetFiles для получения списка файлов. Чем он плох? Какие есть альтернативы?

**Comment by Aloomenon** [comment]
Он плох тем, что если файлов много, то придется дожидаться пока метод отработает + если ловим ошибку, то мы ничего не получим на выходе. Есть альтернатива EnumerateFiles которая создает коллекцию и позволяет работать до момента полного ее заполнения (завершения работы функции)

**Comment by pavel-b-novikov** [comment]
Сформулировано криво, но если выпить 100 грамм - пойдет.
Я не выпил. Но ладно.
